# Generated by Django 3.0.1 on 2019-12-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('school', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
